name: Nightly Scraper

on:
  schedule:
    # Run every 8 hours starting from midnight UTC
    - cron: "0 */8 * * *"  # 00:00, 08:00, 16:00 UTC
    
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check Sydney time (optional - for debugging)
        run: |
          echo "UTC time: $(date -u)"
          echo "Sydney time: $(TZ='Australia/Sydney' date)"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r scrapers/requirements.txt

      - name: Run all scrapers
        working-directory: ./scrapers
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python3 run_all.py