name: Nightly Scraper

on:
  schedule:
    - cron: "0 14 * * *"  # midnight Sydney (AEST). We'll handle DST next.
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps (if any)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scraper
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python3 scrapers/run_all.py
